systems:
  - ['diatomic', 'N', 'N', 1.60151]
  - ['diatomic', 'N', 'N', 1.70828]
  - ['diatomic', 'N', 'N', 1.81505]
  - ['diatomic', 'N', 'N', 1.92181]
  - ['diatomic', 'N', 'N', 2.02858]
  - ['diatomic', 'N', 'N', 2.13535]
  - ['diatomic', 'N', 'N', 2.24212]
  - ['diatomic', 'N', 'N', 2.34889]
  - ['diatomic', 'N', 'N', 2.45565]
  - ['diatomic', 'N', 'N', 2.56242]
  - ['diatomic', 'N', 'N', 2.66919]
  - ['diatomic', 'N', 'N', 2.77595]
  - ['diatomic', 'N', 'N', 2.88272]
  - ['diatomic', 'N', 'N', 2.98949]
  - ['diatomic', 'N', 'N', 3.09626]
  - ['diatomic', 'N', 'N', 3.20302]
  - ['diatomic', 'N', 'N', 3.30979]
  - ['diatomic', 'N', 'N', 3.41656]
  - ['diatomic', 'N', 'N', 3.52333]
  - ['diatomic', 'N', 'N', 3.63009]
  - ['diatomic', 'N', 'N', 3.73686]
  - ['diatomic', 'N', 'N', 3.84363]
  - ['diatomic', 'N', 'N', 3.95040]
  - ['diatomic', 'N', 'N', 4.05716]
  - ['diatomic', 'N', 'N', 4.16393]
  - ['diatomic', 'N', 'N', 4.27070]
  - ['diatomic', 'N', 'N', 4.37747]
  - ['diatomic', 'N', 'N', 4.48423]
  - ['diatomic', 'N', 'N', 4.59100]
  - ['diatomic', 'N', 'N', 4.69777]
  - ['diatomic', 'N', 'N', 4.80454]
  - ['diatomic', 'N', 'N', 4.91130]
  - ['diatomic', 'N', 'N', 5.01807]
  - ['diatomic', 'N', 'N', 5.12484]
  - ['diatomic', 'N', 'N', 5.23161]
  - ['diatomic', 'N', 'N', 5.33837]
  - ['diatomic', 'N', 'N', 5.87221]
  - ['diatomic', 'N', 'N', 6.40605]
